# -*- coding: utf-8 -*-
"""The Hindusthan Times.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HOWV2rGYgFoU0wnNE55aJr85WvuYqPZ2
"""

import requests
from bs4 import BeautifulSoup

# link of a particular article is given as an input.

def content_scrap (link):
  headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
  r = requests.get(link,headers = headers)
  # making a connection request with that particular article

  soup = BeautifulSoup(r.content,'html.parser')
  # getting all the content on a form of HTML parser

  para = soup.find_all('p')
  # scraping all the content with the <p> tag.
  # many a href tag are embedded into <p> tags and therefore need to removed
  
  final_para = ""
  # final context of the article will be scraped and stored in a form of a string name final_para

  # for all the content with <p> tags, if <p> tag contains <href> link then, we will not concante it with final_para string.
  for p in para:
    href = p.find_all('a',href = True)
    if len(href) == 0:
      para_string = p.get_text()
      if len(para_string) != 0 and para_string[len(para_string)-1] != "." :
        adder = ""
      else:
        adder = "."
      final_para = final_para + para_string + adder
  # all the content of p tags have been concatnate with the final_para string

  keywords = soup.find('meta',{'name': 'keywords'})['content']

  #making a dictionary for both final_para and keywords
  Dict = { 'Content' : final_para, 'key_words' : keywords}

  return Dict

def scrap_cell(News_link):
  article_list = []
  headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
  for url_link in News_link:
    # creating a connection requrest with the particular rss feed 
    r = requests.get(url_link,headers = headers)
    soup = BeautifulSoup(r.content, features='xml')
    
    articles = soup.find_all('item')
    for a in articles:
      title = a.find('title').text
      link = a.find('link').text
      content_dict = content_scrap(link)
      article = {
          'title': title,
          'link': link,
          'key_words' : content_dict['key_words'],
          'text' : content_dict['Content']
          }
      article_list.append(article)
  return article_list

News_link = ['https://www.hindustantimes.com/feeds/rss/advertorial/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/analysis/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/astrology/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/astrology/festival/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/astrology/horoscope/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/books/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/brand-post/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/brand-stories/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/budget/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/business/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/bengaluru-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/bhopal-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/chandigarh-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/dehradun-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/delhi-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/gurugram-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/indore-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/jaipur-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/kolkata-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/lucknow-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/mumbai-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/noida-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/others/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/patna-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/pune-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cities/ranchi-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cricket/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/cricket/ipl/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/editorials/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/editors-pick/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/education/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/education/admissions/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/education/board-exams/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/education/competitive-exams/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/education/employment-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/education/exam-results/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/education/news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/assam-assembly-election/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/assam-assembly-election-2016/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/bihar-assembly-election-2020/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/chhattisgarh-assembly-election-2018/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/delhi-assembly-election-2020/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/goa-assembly-election-2017/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/gujarat-assembly-election-2017/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/himachal-pradesh-assembly-election-2017/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/karnataka-assembly-election-2018/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/kerala-assembly-election/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/kerala-assembly-election-2016/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/lok-sabha-election/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/lok-sabha-election-2019/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/madhya-pradesh-assembly-election-2018/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/manipur-assembly-election-2017/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/meghalaya-assembly-election-2018/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/mizoram-assembly-election-2018/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/nagaland-assembly-election-2018/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/puducherry-assembly-election/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/puducherry-assembly-election-2016/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/punjab-assembly-election-2017/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/rajasthan-assembly-election-2018/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/tamil-nadu-assembly-election/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/tamil-nadu-assembly-election-2016/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/telangana-assembly-election-2018/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/tripura-assembly-election-2018/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/us-presidential/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/uttarakhand-assembly-election-2017/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/west-bengal-assembly-election/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/elections/west-bengal-assembly-election-2016/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/entertainment/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/entertainment/bollywood/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/entertainment/hollywood/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/entertainment/music/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/entertainment/others/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/entertainment/tamil-cinema/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/entertainment/telugu-cinema/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/entertainment/tv/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/entertainment/web-series/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/environment/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/health/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-insight/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-insight/climate-change/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-insight/economy/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-insight/education-in-india/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-insight/gender-equality/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-insight/governance/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-insight/international-affairs/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-insight/public-health/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-school/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-school/chronicles/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/ht-weekend/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/htls/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/htls/hindustan-times-leadership-summit-2015/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/htls/hindustan-times-leadership-summit-2016/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/htls/hindustan-times-leadership-summit-2017/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/htls/hindustan-times-leadership-summit-2018/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/htls/hindustan-times-leadership-summit-2019/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/htls/hindustan-times-leadership-summit-2020/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/interactives/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/latest-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/lifestyle/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/lifestyle/art-culture/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/lifestyle/brunch/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/lifestyle/fashion/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/lifestyle/festivals/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/lifestyle/health/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/lifestyle/recipe/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/lifestyle/relationships/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/lifestyle/travel/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/lok-sabha-election-2019/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/nri-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/opinion/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/art-culture/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/brand-stories/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/brunch/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/entertainment/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/ht-school/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/ht-weekend/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/htls/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/lifestyle/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/opinion/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/real-estate/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/singapore-summit/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/sponsoredcontent/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/photos/sports/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/real-estate/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/science/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/singapore-summit/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/sports/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/sports/badminton/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/sports/football/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/sports/hockey/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/sports/olympics/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/sports/others/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/sports/tennis/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/sports/wwe-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/top-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/trending/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/us-diaries/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/coronavirus-crisis/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/cricket/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/election/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/entertainment/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/htls/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/lifestyle/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/shows/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/sponsoredcontent/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/sports/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/videos/world-news/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/work-from-home/rssfeed.xml',
 'https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml']



